apis:
    hosts:
        ip: '192.168.140.241'
        port: 33133
    image_encode:
        route: '/api/image_encode/'
    delete_encode:
        route: '/api/delete_encode/'
    text_search:
        route: '/api/text_search/'
    image_search:
        route: '/api/image_search/'
    semantic_localization:
        route: '/api/semantic_localization/'
data_paths:
    images_dir: '../data/test_data'
    rsd_dir_path: '../data/retrieval_system_data/rsd'
    rsd_path: '../data/retrieval_system_data/rsd/rsd.pkl'
    semantic_localization_path: '../data/retrieval_system_data/semantic_localization_data'
    temp_path: '../data/retrieval_system_data/tmp'
models:
    prefix_path: 'models/'
launch_test:
    test_image: '../data/test_data/images/00013.jpg'
    test_text:  "One block has a cross shaped roof church."

